# -*- restclient -*-
#
# Test commands for restclient for REST API
#
GET http://localhost:3000/api/customers/3
User-Agent: Emacs24
Accept-Encoding: application/json

#
# Post works too, entity just goes after an empty line. Same is for PUT.
#
POST http://localhost:3000/api/customers
Content-Type: application/json

{
        "customer": {
                "dummy" : 1234,
                "name" : "Minion Dave"
        }
}